### ISSUE TITLE
Backend doesn't work

### ISSUE THREAD

**Issue by hockeymikey** [n76/Local-GSM-Backend#120]
I am having no luck getting the backend to work. Initially tried generating the database with https://github.com/sobrus/FastLacellsGenerator using a combination of the three datasets.  Then I tried using the built in database generator.  
Both times I enabled only Local GSM as my location backend, but neither SatStat or OSMAND~ got any cell location fix.  
When I use Mozilla Location Service or Radiocells.org Unified Network location backends, both of those can get cell fixes almost right away.  
I have enabled both the storage and location permissions.
There is nothing really for messages going on in the logs.

I'm running it on Motorola G4 Play, LineageOS 14.1 (Android 7.1.2). Using MicroG 0.2.4-111

Any ideas to further debug or possible solutions?

**Comment by n76** [comment]
I haven't checked the radio cells backend, but the Moxilla backend also collects wifi/lan information so it can return a location even if it does not know about the cell towers.

The first thing is to see if the tower information for your area is in your database. Using SatStat you can look on the icon that looks like a broadcast antenna (third from the left). It should show you the LTE and/or GMS towers your phone detects. There will be MCC, MNC and cell ID information. Next step is to download a recent copy of, say, [the Moxilla database](https://location.services.mozilla.com/downloads). That is simply a ZIP of a comma separated value (CSV) file with all its known cell towers.

See if the tower(s) your phone is detecting is/are in the file. If not, then you have determined the problem. You can use the [Mozilla Stumbler](https://f-droid.org/en/packages/org.mozilla.mozstumbler/) to detect and add towers to their database.

If the towers are in the Mozilla file then the issue is likely that you did not specify your area properly when you built the database for the local GSM database. The easiest way is to select your country and allow for all operators. Double check under "advanced settings" in the backend that the MCC filter contains the MCC code that is on the towers that your phone is detecting.

If the MCC code is not there when you selected your country, then there may be an mistake in the table that defines which MCC codes are used in each country. If you find that the case, please let me know what your country is and what MCC code should be added to it.
