### ISSUE TITLE
Process newly downloaded databases before returning to the settings screen

### ISSUE THREAD

**Issue by Susurrus** [n76/Local-GSM-Backend#13]
The settings screen says that date of the last database downloaded. Unfortunately the database is only actually updated as soon as the next location fix is retried from UnifiedNlp. So even if you download the database and it says everything worked and you click "Finish", the database will not update and the time shown for the last update will be old. This can be confusing for users as they'd expect the new database to be in use immediately and the timestamp to update. Is it possible to move the database updating process to be during the download process?

Since the databases can be generated off the phone and uploaded, I imagine the original reason for this was to use the same codepath for both databases downloaded on the phone and ones processed off of it. Maybe that processing code can just be moved into a function that's called as soon as a new one is downloaded or when a fix is requested.

**Comment by n76** [comment]
The fix for this will probably be combined with a fix for https://github.com/n76/Local-GSM-Backend/issues/10

Basically the download process does exactly the same thing as the offline script with respect to creating a database file and then putting it into .nogapps directory with a .new suffix. Since renames are reportedly broken in ASOP 5.0 (or at least work differently) I will need to rethink how this all should work.

There are some issues on efficiently keeping track of new/old data when building a new database if the download actually processes data on the live (location estimation) database that I have to think through.
