### ISSUE TITLE
Add MNC Filter

### ISSUE THREAD

**Issue by Gitschubser** [n76/Local-GSM-Backend#16]
A MNC Filter (Filtering) would be very great. 
I want to generate the database only with my provider or maybe allow more than one mnc.

**Comment by n76** [comment]
I hadn't thought that was needed some phones will report adjacent cells from other carriers and the more towers one has to work with the better the location estimate.

But it would not be too difficult to add that filter, so look for it in the next week or so.

**Comment by n76** [comment]
MNC filtering added.

**Comment by Gitschubser** [comment]
Perfect, thank you.
Directly generate the new database. :-)

**Comment by Lee-Carre** [comment]
Real-world example of MNC filtering being very useful:

I'm on the island of Jersey. The MCC here is 234. However, that's not exclusive to the island, and seems to be used by various non-mainland British Isles (most of which are so far away as to make their cell sites undetectable from here).

To my knowledge, there are only 3 MNCs operating in Jersey:
* 50 (the incumbent telco, JT)
* 55 (branded as Sure, locally, but really just Cable & Wireless)
* 3 (probably Airtel-Vodafone)

Thus, filtering for only local cells yields a much smaller database. A few thousand entries, instead of closer to a million.

---

Another possibility is if one were a subscriber of a multi-national operator. Filtering for your MNC but **not** MCC (that is, matching any MCC) would yield a database which is useful while travelling (abroad).

**Comment by Lee-Carre** [comment]
The only problem I've encountered with this implementation is that the keyboard is numerical-only. That is, it lacks a comma key (or any means of inputting one) 😄.

This stumped me for a while. The only workaround I discovered was
1. copy a comma character to clipboard from elsewhere
2. when inputting MNCs, long-(tap\|press) to get the context menu
3. select paste
4. continue entering the next MNC
5. repeat steps 2-5 as needed

@deveee
