### ISSUE TITLE
Add Radio Filter

### ISSUE THREAD

**Issue by Gitschubser** [n76/Local-GSM-Backend#17]
A good feature would be to filter the radio (GSM, UMTS, LTE or CDMA).
Maybe a checkbox with all radio could be realized.
Per default GSM, UMTS, LTE and CDMA is selected.
My mobile phone has no LTE or CDMA and i need only the cellids from radio GSM and UMTS.

**Comment by wvengen** [comment]
At the moment this information is not stored in lacells.db, so it would need to be added.
One question would be if these towers are usually at the same position - if so, then it makes sense to use the location of all, so that there is more chance to have a match. Perhaps we could use the radio's cell, and fallback to the average of the other cells.

**Comment by n76** [comment]
Reconsidering this, it seems to me that it would be better for the phone to detect what receiver's it has and automatically limit its database. Having a user checkbox for that will just be complicating the user interface.
