### ISSUE TITLE
CDMA [vzw & sprint], usa

### ISSUE THREAD

**Issue by TameOfGroans** [n76/Local-GSM-Backend#19]
Will this benefit those with CDMA (3G, 1x) handsets with LTE (cat4, cat6)?

**Comment by n76** [comment]
At present the code looks for instances of CellInfoGsm and CellInfoWcdma. I will add code to support CellInfoCdma and CellInfoLte. But even after that I cannot say whether or not OpenCellID and/or Mozilla location services have information about LTE towers in their databases as I do not have a LTE phone to check.

**Comment by n76** [comment]
I don't see data in Mozilla for CDMA or LTE, so closing this until data becomes available.

**Comment by phoneman088** [comment]
Hi, at least on my phone (Sprint EVO 3D with 4.2.2), the API functions for CdmaCellLocation that are supposed to return tower location do actually work. Since CDMA is required to have a GPS receiver at the tower for synchronization purposes, this information is probably just broadcast by the tower itself. There is actually no need for a database, but adding code to just return the coordinates provided by the API in the case of CDMA should be trivial.
