### ISSUE TITLE
Using of Signal Strength should improve location accuracy

### ISSUE THREAD

**Issue by a-ni** [n76/Local-GSM-Backend#26]
You can add Signal Strength (getCellSignalStrength) in the weight to improve location calculation. As stronger signal as closer to the tower.

**Comment by agilob** [comment]
This code could be just copied from WIGLE, but from my experience it's very inaccurate, sometimes it located me a few kilometres away from actual location.

**Comment by n76** [comment]
Do you have a phone that supports either the getNeighboringCellInfo() or getAllCellInfo() calls in TelephonyManager? The one phone I have to work on this returns null and/or empty depending on which call I try. The result is that I can only test with the one tower that is returned by getCellLocation() so I can't adequately test any type of averaging.

If you have a phone that supports that and are willing to help, I can code up an signal strength weighted average location estimate for you to test.

**Comment by a-ni** [comment]
How can I check this? I've found in my phone's EngineeringMode menu on NetworkInfo_Info page information about Neighboring Cells that consists of: neigh_cell_count (and then for each cell) cellid, arfcn, psc, qQualmin, qRxlevmin, srxlev, squal, rscp & ec_no. Will this be helpful?

**Comment by n76** [comment]
Sounds like it. I'll work up the changes needed to use received signal strength in the weighted averaging. It may take a few days for me to get too it. By the way, what version of Android are you running?

**Comment by a-ni** [comment]
4.2.1, but I can engage a friend of mine in testing as well. He use 5.0 or 5.1

**Comment by baongoc124** [comment]
I'm interested in this too. Could I give any help? I'm running on 5.1.1.

**Comment by zoff99** [comment]
+1

**Comment by agilob** [comment]
I checked this and it's harder than you think. There are dozens of variables that add noise to estimating location, let's list a few of the most important:
* devices incorrectly implement and provide signal strength
* BTS has latitude, longitude and... altitude
* I took some measures and even non-moving device gets signal strength varying by 5-14dB very n-seconds
* weather conditions don't help
* different signal strength is used for 2G, 3G and 4G networks, we would have to relay on correct implementation for each of them for all devices, tested it on 6 devices, 4 different Samsung models and 2 LGs, each had different problem

if you know how to overcome those problems... write scientific paper about it.

**Comment by zoff99** [comment]
start with using neighbouring cellinfo, and if you have more than 1 celltower just use the geometric middle between all tower locations.

that would be a prgmatic thing to start with?
i guess more accurate than just 1 tower location

**Comment by agilob** [comment]
4 devices I tested don't provide at least one of:

* signal for neighbouring cells
* CID 
* LAC 
* technology 
* MCC/MNC

Do you want to test my app that I was working on?

**Comment by n76** [comment]
The backend already attempts to use as many towers as it can get information for using the TelephonyManager.getAllCellInfo() and TelephonyManager.getNeighboringCellInfo() method calls. And it does a geometric mean (inversely weighted on reported tower coverage range) on the towers it can get information for to estimate position.

The issue is that many phones return null on the TelephonyManager.getAllCellInfo() and TelephonyManager.getNeighboringCellInfo() method calls. On those phones the only information you have is for the one tower you are connected to. No matter how you calculate it, your position will be the tower location with your uncertainty the reported tower range.

And, as of a year or so ago, Samsung phones are in the group that only report the one tower you phone is connected to. So for a major portion of the user base the current code does as well as is possible.

**Comment by Lee-Carre** [comment]
> as of a year or so ago, Samsung phones are in the group that only report the one tower you phone is connected to.

On my SM-A405FN (purchased 2019Q3) several apps list multiple entries for neighbouring cells.
