### ISSUE TITLE
lacells directory

### ISSUE THREAD

**Issue by DJaeger** [n76/Local-GSM-Backend#58]
Allow to define a custom directory, to store the lacells.db, inside the expert settings.

**Comment by herrdeh** [comment]
me2!

**Comment by IzzySoft** [comment]
Especially as 1.3.6 removed access to the remotely generated database, it's completely unclear where to place the `lacells.db` file now. In previous versions, one could define that location in settings, which is no longer the case. I don't want to generate a database on each of my devices separately – so I do so on my computer and push the resulting file to all devices. Where to? So please, let us define the location again!

**Comment by n76** [comment]
Try placing the lacells.db within the /sdcard/Android/data/org.fitchfamily.android.gsmlocation/files/ directory.

I would like to pick a non-hidden, non-protected place where you could place a new lacells.db. I am leaning toward /sdcard/Download with a UI option to then grab that file. Does this sound reasonable?

**Comment by IzzySoft** [comment]
@n76 Any location that can be *set* with the UI should be fine (let the user define). For my described case, pushing it to the download folder *and then having to manually import it* would be a show-stopper: the push is done automatically, manual actions would be forgotten too often. So I'd then prefer a defined and documented directory even if it's hard coded (I can definitely live with `/sdcard/Android/data/org.fitchfamily.android.gsmlocation/files/` if it's that) – but before I update again to the latest version (I'm currently using an ancient one again from a backup) I must be sure the file is found :)

Btw: while the app's own data directory sounds like a logical choice here, before "hard coding" that we should be sure there's no other app that might wish to use this database – because then it's the "logical choice" no longer. I think e.g. of an app that *records* into the file (data collector, e.g. "whenever there's GPS enabled and we've got a fix, record cells"), or some app using the database for cell information on "signal tracking". If that's a possibility, some "shared location" should be preferred.

However, having `/sdcard/Android/data/org.fitchfamily.android.gsmlocation/files/` as *default location* is fine, but the user should be able to chose a different one the LocationBackend is checking then (without "manual import").

**Comment by IzzySoft** [comment]
@n76 I've just checked on another device, where I've started using this backend in a very early state and always kept it up-to-date (runs the latest version now). There it still reports the latest database, which is still located in the `.nogapps` directory.

**Can you confirm that, if on the new device I start with an old version still using the `.nogapps` location and configure it there, updating to the latest version would adopt that configuration?**

In that case, a work-around (until you implement a "storage location picker" again) might be installing such an old version, configure it, and then (optionally) update to the latest version. You could then point to a download location of the corresponding "old APK" (e.g. in the F-Droid archive repo), so people can "help themselves" in the meantime.

**Comment by IzzySoft** [comment]
@n76 

> It looks like the logic to check for database files at /sdcard/.nogapps is still in the code and the backend should look for them and move them when it is started. So for your scripted application, you could continue to put files in that location and then force stop the backend. When UnifiedNlp restarts it, you should have you most recent database file.

That would explain why it still works on my LG P880. I always place the new file in `/sdcard/.nogapps`, and still the UI shows the latest one. However, on my *Wileyfox Swift* (fresh install) it didn't do that but told me there's no database found.

Note: I don't want to have a different "logic" per device in my script. And I'd prefer a path that's easy to remember. `.nogapps` matches that :)

**Comment by n76** [comment]
The database location changed to the official app file area with v1.3.3. On v1.3.5 I removed the migration code. But there were issues with external file access by some users, so I restored (but not really tested the code) in v1.3.7

As it stands, the migration code is only executed when the backend is instantiated, so you need to get the OS to kill it. (UnifiedNlp and/or GmsCore will restart it.)

If I understand your use case, you are doing an offline generation and then would like to push the result to multiple phones. Thus you would like a standard place to push the files to. Is that correct?

Would a version of the code that while running (as opposed to merely at startup) checks for a database at /sdcard/.nogapps/lacells.db.new and treats it the same as one generated on the phone work for you? If so, I build up a test version which you and let me know if it works before I release it.

**Comment by n76** [comment]
@IzzySoft - Try [this version I just put on DropBox](https://dl.dropboxusercontent.com/u/19663978/gsmLocation.apk). It makes a check for the existence of a readable file named `lacells.db.new` in the old `.nogapps` directory and if so, closes its current database, moves the new file and then starts using it. Identical logic to the transition of a new database downloaded by the internal database generation logic. This won't be the formal release as it has additional debug logging enabled, but other than changing the logging, should be good to go.

**Comment by IzzySoft** [comment]
I still feel it strange that on at least one device it works just placing the file as `/sdcard/.nogapps/lacells.db` (without the `.new` prefix), though I have a quite recent version installed there (1.4.1 I believe), and would prefer keeping it that way. But yeah, adding that suffix would work as well. "Allow to define a custom directory" (as the original poster requested) and simply replace the `lacells.db` there is not an option?

Apart from that "moaning", there's something appealing in your new suggestion: while it would require twice the disk space of the `lacells.db` file (at least for a short time), it would ensure the Backend takes care for the replacement itself and doesn't "get confused" having it replaced while running. So I'll pick the test version and give it a go later this week (time's a bit packed right now, but towards the end of the week I should find some to experiment). So thanks a lot!

**Comment by dicer** [comment]
I also like the configurable directory better. My usecase: Internal space is limited and of course Android points /sdcard/ to internal space... I'd much rather use my actual sdcard! Also because of several other apps putting big things on internal "SD" already.

Maybe have that in some kind of expert settings?

**Comment by IzzySoft** [comment]
Thanks a lot! That should indeed end the discussion. Except, maybe, questions for a file picker :) For a ready solution, maybe [MaterialFilePicker](https://github.com/nbsp-team/MaterialFilePicker) could be a matching choice?

**Comment by n76** [comment]
A pull request with a directory picker enhancement change would be reviewed and may be accepted.

**Comment by IzzySoft** [comment]
Unfortunately I cannot do that – never did any Android development :) But maybe someone else can jump in?

**Comment by IzzySoft** [comment]
@n76 PS: Moving the database from wherever the user has configured it to be into "the realm of the app" (`sdcard/Android/data/org.fitchfamily.android.gsmlocation/files`) has another nasty side-effect: `adb backup org.fitchfamily.android.gsmlocation` gets blown pretty large, as it then includes the database, which might be several hundred MB (additionally; in my case it is 250MB+) – which I'm just experiencing here, preparing my device for a new Android version: backup just of this one app already runs for more than 45min and still is not completed, estimated size of the backup file is 110MB+ (I've cancelled the backup after 1h as the file size no longer changed).

As the database can be recreated any time or, if needed, backed up by other means, this is far from being ideal: in case a restore is wanted, that certainly doesn't include an outaged cell database – which one then had to update anyway. So IMHO this just unnecessarily wastes time on backup and restore which is why I think if the user configures an alternative directory, the file should stay there (and not be moved over).

If I shall open a new issue for that, please let me know.

**Comment by n76** [comment]
Looks like the databases ought to be put in `getNoBackupFilesDir()` rather than `getFilesDir()`. If I read the documentation correctly, that should keep them from being backed up to the cloud and maybe on local backups too.

**Comment by n76** [comment]
Present version of app simply uses the directory specified by the user, or if none specified then it uses `context.getExternalFilesDir(null)` which [according to the docs that directory is not backed up](https://developer.android.com/training/backup/autosyncapi.html). And a quick check shows that it is not backed up on my device:
```
$ adb shell
shell@tuna:/ $ls -l sdcard/Android/data/org.fitchfamily.android.gsmlocation/files
-rw-rw---- u0_a56   sdcard_rw 265093120 2016-06-07 09:51 lacells.db
-rw-rw---- u0_a56   sdcard_rw 262356992 2016-05-27 16:58 lacells.db.bak
-rw-rw---- u0_a56   sdcard_rw  1285036 2016-06-18 11:45 lacells_gen.log
shell@tuna:/ $ exit
$ adb backup org.fitchfamily.android.gsmlocation
Now unlock your device and confirm the backup operation.
$ ls -l backup.ab 
-rw-r-----  1 tfitch  staff  549 Jun 25 08:29 backup.ab
MacBook-Pro:~ tfitch$ 
```

**Comment by IzzySoft** [comment]
> Present version of app simply uses the directory specified by the user […]

Was not the case here. I'm using your app for quite a while, and always applied the updates – but not (yet) entered a specific directory (which I'm doing now when setting it up again). When I had a new database created on my Linux machine, I've pushed it to `/sdcard/.nogapps`. Did nothing else. GSMBackend seems to have noticed that "new file" at some point, and "adopted" it – as it disappeared from `/sdcard/.nogapps`. This was still the case with the latest version (updated from "long ago" until now).

Might behave different with a "fresh installation" and the directory specified explicitly – but as described above, I've ended up with a 110MB broken backup file after 1h. I'm just doing a fresh install currently. Will try another backup later then (when done configuring my device) and report back.

Thanks for the fast response!

Oh, PS: It did it again:

1. `/sdcard/.nogapps/lacells.db` was already there (I've just pushed a fresh file)
1. Installed GSMLocation from F-Droid
1. Opened its interface via µG Settings.

Said: "Last database update: today". And checking for `/sdcard/.nogapps/lacells.db`: Gone.

**Comment by n76** [comment]
There are two conflicting things here:

1. For "normal" users (who use the app's built in facility to download and build a database), to migrate from the old` /sdcard/.nogapps/lacells.db` to app controlled storage.
2.  For "advanced"users (who generate databases off line and push it to the phone) to be able to specify a directory of their choice.

I guess a third option would be for users who use the built in database creation but would rather have the database someplace else,maybe on a real SD card instead of using up relatively valuable built-in storage.

If you wish to have your data in `/sdcard/.nogapps/` then under the advanced settings specify that directory. On start up it should (not thoroughly tested) move the files from `/sdcard/.nogapps/` to `/sdcard/.nogapps/` (basically a no-op) and then run as you expect. On the other hand, if you wish to download the files from your PC to a directory of your choice then picking the old hidden directory is not one that I'd pick. I'd probably go for a visible directory someplace, probably a subdirectory under `/Download`.

**Comment by IzzySoft** [comment]
Agreed. It's just that I have to update and adjust several devices and scripts :)

While I can live with a "works as designed", I'd still suggest to *point this out explicitly* (which is what I was doing). Good point with the "visible directory" (especially one other than the old `.gapps`) to avoid confusion – though that directory is still used by e.g. BlankStore (from the old NOGAPPS project), and I like to keep things together :)

Thanks for pointing out the details!
