### ISSUE TITLE
Confusing settings labels

### ISSUE THREAD

**Issue by kuba-orlik** [n76/Local-GSM-Backend#76]
I have a hard time understanding the setting options.

> Option 1: "Download all areas and only save chosen" 

What does it do? Does it download all of the areas, or only the ones chosen in the "Areas" section?

**Comment by n76** [comment]
Data from both Mozilla and OpenCellID are simply one large file that contains entries for the entire world (all areas). With this option your phone will download the file(s) from those sources but it will only save into your on-phone database information about the towers for the country or countries that you have selected.

The other option "Download chosen areas from lacells (data may be old)" fetches data for the specific countries you have selected from [extracts that are generated by @wvengen](https://github.com/wvengen/lacells) from the same Mozilla/OpenCellID sources. Those extracts are not generated everyday, so the data will be older than if you use the first option. If you choose this option then you phone will have to download less data because all the filtering has been done when making the extracts. However there are some MCCs (mobile country codes) which are not found in the extracts so this might fail if the countries you select are not found in the extracts.

**Comment by kuba-orlik** [comment]
Thank you for the explanation! :)
