### ISSUE TITLE
Neighboring cells

### ISSUE THREAD

**Issue by ghost** [n76/Local-GSM-Backend#80]
You are right it is impossible.

**Comment by n76** [comment]
It already attempts to use all the cell towers the phone reports. However:

1. Many phones, especially those from Samsung, return a null or empty list when asked about adjacent cells or for all cells.
2. My phone is among those which gets an empty list of adjacent cell towers, so I have trouble testing this.

If your phone does return good values from either the older adjacent towers API or the newer all cell information API and you are willing to work with me on this we can improve the situation. If you use [an app like SatStat](https://f-droid.org/repository/browse/?fdfilter=satstat&fdpage=1&page_id=0) you can get a list of towers the phone is reporting. If there is more than one tower shown, and you are willing to help, please let me know.

**Comment by catFreeAndroid** [comment]
Sorry for the delay.

I already had SatStat installed. After trying what you said, it seems that my phone is behaving the way you described. It detects other cells and even their signal strength, but the cellid value is missing for all neighboring cells. To protect my privacy, since this discussion is public, I've omitted the cellid value for the current cell in use.

It's really a shame the hardware folks don't provide the necessary support for awesome developers like yourself. If there is anything else I can do please let me know!

Nexus 5x (MTC20F)
cm-13.0-20160830-NIGHTLY-bullhead.zip
SatStat Version 3.1 from F-Droid

![scr](https://cloud.githubusercontent.com/assets/21297296/18088487/dff087c6-6eb2-11e6-8019-93c08e11a789.png)
